default_language_version:
  python: python

repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.4.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  -   repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
      - id: black

  -   repo: https://github.com/pre-commit/mirrors-pylint
      rev: v3.0.0a5
      hooks:
      - id: pylint
        args: [--disable=E0401, --disable=R0903]

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
      - id: mypy
        args: [--config-file=mypy.ini]
