stages:
  data_ingestion:
    cmd: python src/cnn_classifier/pipeline/data_ingestion_pipeline.py
    deps:
      - src/cnn_classifier/pipeline/data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data


  prepare_model:
    cmd: python src/cnn_classifier/pipeline/prepare_model_pipeline.py
    deps:
      - src/cnn_classifier/pipeline/prepare_model_pipeline.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_model


  model_training:
    cmd: python src/cnn_classifier/pipeline/model_training_pipeline.py
    deps:
      - src/cnn_classifier/pipeline/model_training_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/prepare_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/model_training/model.h5


  model_evaluation:
    cmd: python src/cnn_classifier/pipeline/model_evaluation_pipeline.py
    deps:
      - src/cnn_classifier/pipeline/model_evaluation_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/model_training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false
