AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 20
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
VALIDATION_SPLIT: 0.2
INTERPOLATION: "bilinear"
ROTATION_RANGE: 40
HORIZONTAL_FLIP: True
WIDTH_SHIFT_RANGE: 0.2
HEIGHT_SHIFT_RANGE: 0.2
SHEAR_RANGE: 0.2
ZOOM_RANGE: 0.2
SHUFFLE: False
VALIDATION_SUBSET: "validation"    # can be training, validation, both
TRAINING_SUBSET: "training"
