artifacts_root: artifacts


data_ingestion:
  root_directory: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1oiTnXuWyL5oN6E4d-EmyplBj68ife5MJ/view?usp=drive_link
  downloaded_data_file: artifacts/data_ingestion/data.zip
  unzip_directory: artifacts/data_ingestion
